apps/bifrost/lib/bifrost_web/router.ex
defmodule BifrostWeb.Router do
  use BifrostWeb, :router

  import Phoenix.LiveDashboard.Router
  import Plug.BasicAuth

  pipeline :private_browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BifrostWeb.LayoutView, :root}
    plug :protect_from_forgery

    plug :put_secure_browser_headers,
         %{
           "content-security-policy" => "\
            default-src 'self';\
            script-src 'self' 'unsafe-inline' 'unsafe-eval';\
            style-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com;\
            img-src 'self' 'unsafe-inline' 'unsafe-eval' data:;\
            font-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.gstatic.com data:;\
          "
         }

    plug :basic_auth, Application.compile_env(:bifrost, :basic_auth)
  end

  pipeline :public_browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {BifrostWeb.LayoutView, :root}
    plug :protect_from_forgery

    plug :put_secure_browser_headers,
         %{
           "content-security-policy" => "\
            default-src 'self';\
            script-src 'self' 'unsafe-inline' 'unsafe-eval';\
            style-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.googleapis.com;\
            img-src 'self' 'unsafe-inline' 'unsafe-eval' data:;\
            font-src 'self' 'unsafe-inline' 'unsafe-eval' https://fonts.gstatic.com data:;\
          "
         }
  end

  pipeline :graphql_api do
    plug :accepts, ["json"]

    plug HeimdallQL
  end

  scope "/", BifrostWeb do
    pipe_through :private_browser

    live "/", PageLive, :index

    resources "/encrypted_messages", EncryptedMessageController, only: [:new, :create, :delete]
  end

  scope "/", BifrostWeb do
    pipe_through :public_browser

    live "/encrypted_messages/:id", EncryptedMessageLive, :show
  end

  scope "/api/graphql" do
    pipe_through [:graphql_api]

    forward "/", Absinthe.Plug, schema: HeimdallQL.Schema
  end

  # coveralls-ignore-start
  if Mix.env() == :dev do
    forward "/graphiql", Absinthe.Plug.GraphiQL,
      default_url: "/api/graphql",
      schema: HeimdallQL.Schema,
      socket: BifrostWeb.UserSocket,
      interface: :advanced
  end

  # coveralls-ignore-stop

  # Enables LiveDashboard only for development
  scope "/" do
    pipe_through :private_browser
    live_dashboard "/dashboard", metrics: BifrostWeb.Telemetry
  end
end

apps/bifrost/lib/bifrost_web/controllers/encrypted_message_controller.ex
defmodule BifrostWeb.EncryptedMessageController do
  use BifrostWeb, :controller

  def new(conn, _params), do: render(conn, "new.html", conn: conn)

  def create(conn, %{"encrypted_message" => encrypted_message_params}) do
    args = parse_encrypted_message_args(encrypted_message_params)

    case apply(SecureStorage, :insert_encrypted_message, args) do
      {:ok, encrypted_message} ->
        conn
        |> put_flash(:info, "Inserted encrypted_message #{encrypted_message.id}")
        |> redirect(to: "/")

      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    case SecureStorage.delete_message(id) do
      {:ok, _} ->
        conn
        |> put_flash(:info, "Deleted encrypted_message #{id}")
        |> redirect(to: "/")

      {:error, _} ->
        conn
        |> put_flash(:error, "Cannot find encrypted_message with id: #{id}")
        |> redirect(to: "/")
    end
  end

  defp parse_encrypted_message_args(encrypted_message_params) do
    params = Map.drop(encrypted_message_params, ["raw", "key"])

    [
      Map.fetch!(encrypted_message_params, "raw"),
      Map.fetch!(encrypted_message_params, "key"),
      params
    ]
  end
end

apps/bifrost/lib/bifrost_web/live/encrypted_message_live.ex
defmodule BifrostWeb.EncryptedMessageLive do
  use BifrostWeb, :live_view

  @impl true
  def mount(%{"id" => id}, _session, socket) do
    message = SecureStorage.get_message(id)

    {:ok, assign(socket, message: message, result: nil, show: false)}
  end

  @impl true
  def handle_event("decrypt", %{"key" => key, "id" => id}, socket) do
    message = SecureStorage.get_message(id)

    case message && SecureStorage.decrypt_message(message, key) do
      nil ->
        {:noreply,
         socket
         |> put_flash(:error, "Secure data not found. Maybe it expired...")
         |> assign(message: nil, result: nil, show: false)}

      {:error, :decryption_error} ->
        message = SecureStorage.get_message(id)

        {:noreply,
         socket
         |> put_flash(:error, "Error in decryption")
         |> assign(message: message, result: nil, show: false)}

      {:error, :no_attempts_remaining} ->
        message = SecureStorage.get_message(id)

        {:noreply,
         socket
         |> put_flash(:error, "No Attempts remaining")
         |> assign(message: message, result: nil, show: false)}

      {:error, :no_reads_remaining} ->
        message = SecureStorage.get_message(id)

        {:noreply,
         socket
         |> put_flash(:error, "No Reads remaining")
         |> assign(message: message, result: nil, show: false)}

      {:ok, decrypted} when is_binary(decrypted) ->
        message = SecureStorage.get_message(id)

        {:noreply,
         socket
         |> put_flash(:info, "Message decrypted and ready to copy to clipboard")
         |> assign(message: message, result: decrypted, show: false)}
    end
  end

  @impl true
  def handle_event("show", _, socket) do
    {:noreply,
     socket
     |> assign(show: true)}
  end

  @impl true
  def handle_event("hide", _, socket) do
    {:noreply,
     socket
     |> assign(show: false)}
  end
end

apps/bifrost/lib/bifrost_web/views/encrypted_message_view.ex
defmodule BifrostWeb.EncryptedMessageView do
  use BifrostWeb, :view
end

apps/bifrost/lib/bifrost_web/templates/encrypted_message/new.html.eex
<%= form_for :encrypted_message, Routes.encrypted_message_path(BifrostWeb.Endpoint, :create), fn f -> %>
  <%= label f, :raw, class: "control-label" %>
  <%= textarea f, :raw_mask %>

  <%= textarea f, :raw, hidden: true %>

  <%= label f, :key, class: "control-label" %>
  <%= password_input f, :key %>

  <%= label f, :short_description, class: "control-label" %>
  <%= text_input f, :short_description %>

  <%= label f, :description, class: "control-label" %>
  <%= textarea f, :description %>

  <%= label f, :encryption_algo, class: "control-label" %>
  <%= select f, :encryption_algo, ~w(aes_gcm plain), selected: "aes_gcm" %>

  <%= label f, :ttl, "TTL (in minutes)", class: "control-label" %>
  <%= number_input f, :ttl, value: 5 %>

  <%= label f, :max_attempts, "Max Attempts (default: 999)", class: "control-label" %>
  <%= number_input f, :max_attempts, value: 999 %>

  <%= label f, :max_reads, "Max Reads (default: 999)", class: "control-label" %>
  <%= number_input f, :max_reads, value: 999 %>

  <br />
  <%= submit "Insert Secure Data" %>
<% end %>

<script>
  let rawMask = document.getElementById("encrypted_message_raw_mask")
  let rawValue = document.getElementById("encrypted_message_raw")

  rawMask.addEventListener("blur", _event => {
    console.log(rawMask.value)
    rawValue.value = rawMask.value
    value = rawMask.value.replaceAll(/./g, "*")
    console.log(rawMask.value)
    rawMask.value = value
  })

  rawMask.addEventListener("focus", _event => {
    rawMask.value = rawValue.value
  })
</script>